matching_groups:
  - /api/tag
  - /api/user/[^\/]+/theme
  - /api/user/[^\/]+/livestream
  - /api/user/[^\/]+/statistics
  - /api/user/[^\/]+/icon
  - /api/user/me
  - /api/livestream/reservation
  - /api/livestream/search
  - /api/livestream
  - /api/livestream/[^\/]+
  - /api/livestream/[^\/]+/livecomment
  - /api/livestream/[^\/]+/reaction
  - /api/livestream/[^\/]+/report
  - /api/livestream/[^\/]+/ngwords
  - /api/livestream/[^\/]+/moderate
  - /api/livestream/[^\/]+/enter
  - /api/livestream/[^\/]+/exit
  - /api/livestream/[^\/]+/livecomment/[^\/]+/report
  - /api/register
  - /api/login
  - /api/icon
  - /api/payment
sort: avg
reverse: true
metrics:
  - count
  - method
  - uri
  - min
  - avg
  - max
  - sum
  
file: /var/log/nginx/access.ndjson
